run:
  skip-files:
    - migration/sqlbindata.go
  skip-dirs:
    - design/*

linters:
  disable:
    - lll
    - gosec
    - prealloc
  enable-all: true

issues:
  exclude-use-default: false
  exclude:
    - .*, which can be annoying to use.*
    - .((os\.)?std(out|err)\..*|.*Close|.*Flush|.*Write|.*Serve|os\.Remove(All)?|.*printf?|os\.(Un)?Setenv).

output:
  format: line-number